In [1]:
import numpy as np
from abc import ABC, abstractmethod

In [2]:
class Layer(ABC):
    @abstractmethod
    def __init__(self):
        pass
    
    @abstractmethod
    def forward(self, x):
        pass
    
    @abstractmethod
    def backward(self, grad):
        pass

In [3]:
class GradTensor:
    def __init__(self, tensor):
        self.data = tensor
        self.shape = self.data.shape
        self.grad = None
    
    def _zero_grad(self):
        self.grad = None

In [ ]:
class LinearLayer(Layer):
    def __init__(self, in_features: int, out_features: int):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        self.weight = GradTensor(np.random.rand(
            self.in_features,
            self.out_features
        ))

        self.bias = GradTensor(np.zeros(
            self.out_features
        ))
    
    def forward(self, x):
        self.x = x
        return x @ self.weight.data + self.bias.data
    
    def backward(self, grad):
        self.weight.grad = np.matmul(self.x.T, grad) # (I x O) --> (I x B) @ (B x O)
        self.bias.grad = np.sum(grad, axis = 0, keepdims=True)
        return np.matmul(grad, self.weight.grad.T)
    
    def __call__(self, x):
        return self.forward(x)

In [10]:
class LayerNorm(Layer):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return super().forward(x)
    
    def backward(self, grad):
        return super().backward(grad)

In [13]:
batch = 10
in_features = 3
out_features = 2
x = np.random.rand(batch, in_features)
layer_1 = LinearLayer(in_features, out_features)
logits = layer_1.forward(x)
layer_1.backward(np.random.rand(batch, out_features))

array([[3.19835457, 2.60887008, 2.54448355],
       [2.44974799, 1.99241867, 1.89918973],
       [2.51958122, 2.04994389, 1.95955622],
       [1.42285689, 1.15648162, 1.09667082],
       [4.47377756, 3.64293928, 3.5054724 ],
       [2.11842688, 1.71867948, 1.60583518],
       [3.68810939, 2.99511961, 2.82097349],
       [4.01654972, 3.26558831, 3.10416847],
       [4.6069889 , 3.7488411 , 3.58788491],
       [3.35428072, 2.72303364, 2.55723163]])

In [24]:
x = np.random.rand(2, 4)
np.sum(np.exp(x) / np.sum(np.exp(x), axis = 1, keepdims=True), axis = 1)

array([1., 1.])

In [25]:
x

array([[0.66285969, 0.10254925, 0.85842851, 0.06112212],
       [0.47481765, 0.19919509, 0.89797833, 0.98335875]])

In [26]:
np.exp(x) / np.sum(np.exp(x), axis = 1, keepdims=True)

array([[0.29985969, 0.17122941, 0.36463012, 0.16428079],
       [0.20207154, 0.15339238, 0.3085187 , 0.33601738]])